### ISSUE TITLE
PJSIP undefine standard UNIX macros s_addr and s6_addr

### ISSUE THREAD

**Issue by aberaud** [pjsip/pjproject#2311]
In `sock.h` and `compat/socket.h`,  PJSIP undefines crucial macros from the UNIX standard library:

```c
#undef s_addr
#undef s6_addr
#undef sin_zero
```

This breaks any program using PJSIP and making use of these standard-library macros/fields.

For instance it makes impossible to use PJSIP along with ASIO, because ASIO makes use of these standard-library macros:

```
/include/asio/ip/impl/address_v6.ipp:56:16: error: no member named 's6_addr' in 'in6_addr'
  memcpy(addr_.s6_addr, bytes.data(), 16);
```
PJSIP, like any proper C/C++ program or library, should never undefine or redefine UNIX or standard library macros and symbols.

**Comment by aberaud** [comment]
A solution might be to define a pjsip version of the macro only if the macro is undefined ?

**Comment by sauwming** [comment]
PJSIP library itself seems to build just fine if I remove those macro undefinitions.
However, if in my app, I include headers which define those macros, such as `<netinet/in.h>` then it will fail to compile with an error:
```
../include/pj/sock.h:549:17: error: expected ';' at end of declaration list
    pj_uint8_t  s6_addr[16];   /**< 8-bit array */
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/netinet6/in6.h:159:28: note: 
      expanded from macro 's6_addr'
#define s6_addr   __u6_addr.__u6_addr8
```

The reason we undefine those macros is because we use it do declare our IPv4/6 address structure, such as:
```
/* Must undefine s_addr because of pj_in_addr below */
//#undef s_addr
typedef struct pj_in_addr {
    pj_uint32_t	s_addr;		/**< The 32bit IP address.	    */
...
#undef s6_addr
typedef union pj_in6_addr {
    pj_uint8_t  s6_addr[16];   /**< 8-bit array */
```

So the solution seems to be to rename the struct member names to something else. But then, I'm not sure why we insisted to use such conflicting names in the first place. Perhaps @nanangizz can comment on this issue?

**Comment by sauwming** [comment]
We have tried fixing this issue in #2313, however as we found out later, it creates a lot of complications, causes build failures on other platforms, raises portability issue, not to mention the obvious one, breaking current existing apps. The only positive I get is that I now understand the reason why we chose to undefine those macros last time.

While it's true that a proper C/C++ program or library should never undefine or redefine UNIX or standard library macros and symbols, I believe a proper C/C++standard library shouldn't arbitrarily define a **non-reserved** keyword as well.

So, we're currently still weighing whether the benefits outweigh all the consequences. For a workaround, I would suggest to include ASIO headers first before PJSIP. Please let us know if this works for you.

**Comment by aberaud** [comment]
Greetings and thank you very much for having tried to fix this !

We expected it would be complicated to fix for you, and we're working on workarounds on our side.
Best regards

**Comment by traud** [comment]
Not sure if it helps, but this is the way it is solved in Digium Asterisk 11 since 2012 which re-uses PJProject:

1. https://issues.asterisk.org/jira/browse/ASTERISK-20366
2. https://issues.asterisk.org/jira/browse/ASTERISK-27997
3. https://github.com/asterisk/asterisk/commit/603d1e8d4b45cc3e73f7c000dc6adf93310ef5eb

If that is needed only for [Windows](http://trac.pjsip.org/repos/changeset/484), I wondered, why not guard it with [\_\_unix\_\_](https://stackoverflow.com/a/7063372)? Anyway, the patch above should do the trick for [UNIX System V](https://en.wikipedia.org/wiki/UNIX_System_V) based operating systems.
