### ISSUE TITLE
Make transport count in pjsua as compile level define constants

### ISSUE THREAD

**Issue by vit1251** [pjsip/pjproject#2325]
**Is your feature request related to a problem? Please describe.**

Component ```pjsua``` source code contain ```struct pjsua_data``` with transport array with 8 slots in hardcode manner. 

**Describe the solution you'd like**

How about create ```define``` with value of transport count. For example my deskphone contain 32 buttons for SIP registrations and I assume that is known as transport in pjsua.

**Describe alternatives you've considered**

I can suggest remove endpoint instance (singletone) and provide on pjsip make multiply count of endpoint instead single one.

**Additional context**

No.

**Comment by trengginas** [comment]
the tpdata represent the transport/listener created from pjsua_transport_create(). It doesn't represent the account. 
e.g: 
* on your case, multiple accounts registered using UDP.
  - create UDP transport (single)
  - add account (multiple), max: `PJSUA_MAX_ACC`
  - the library will create the 'client' transport to send (SIP) messages when needed.

We rarely have a scenario where we would need multiple listener. However since we have #1019, this

**Comment by vit1251** [comment]
@trengginas I want to have ability to separate outgoing SIP stream by src port. For example first account on 5061, second account 5062 and etc. This provide ability to understand on large logs  and provide way to capture SIP more split for debugging.
