### ISSUE TITLE
 Too many objects of the  specified type (PJ_ETOOMANY) [status=70010]

### ISSUE THREAD

**Issue by tangxiangpi** [pjsip/pjproject#2400]
on android 10 huawei pjsip 2.9.
when app is on background for a long time may 30m, the network for app may be not useable,
pjsip will re-register always ,but sometimes  ....SIP registration failed, status=503 (Too many objects of the  specified type (PJ_ETOOMANY) [status=70010],how can i avoid this problem ？
can i increase PJ_IOQUEUE_MAX_HANDLES to  avoid this problem?

[core_20200423.xlog.log](https://github.com/pjsip/pjproject/files/4520085/core_20200423.xlog.log)

**Comment by tangxiangpi** [comment]
How to reappear ？
just like this：
            for(int i=0;i<200000;i++){
                Log.e(THIS_FILE,"when get error ? " + i);
                accountMgr.setRegistration(true); // call pjsua_acc_set_registration(true)
                accountMgr.setRegistration(false);//call pjsua_acc_set_registration(false)
            }

**Comment by tangxiangpi** [comment]
anybody here?

**Comment by sauwming** [comment]
If you send out many registration requests, obviously at one point, it will be more than what the library can handle, which is why the ETOOMANY error.

As for the solution, if the network is down, app needs to detect it and prevent any operation that requires network, since it will be useless anyway.

For further questions, please use any other means such as StackOverflow. Currently issue is for bug report or feature request only.

**Comment by tangxiangpi** [comment]
The network is actually available, but the system restricts the app's access to the network. This usually happens after the app enters the background for a period of time, and the app can't always check whether the network is available. From the log, this problem occurs after only registering for more than 120 times. Most of these registers are also pjsip's own attempt to actively register, which is reasonable. I don't think it should be The app avoids it, but pjsip itself has vulnerabilities in some cases
