### ISSUE TITLE
ioqueue assert when many calls arrive

### ISSUE THREAD

**Issue by ilogixxDE** [pjsip/pjproject#2617]
we are currently on version 2.10 on windows 10/2019 Server. We ran into an issue where we get an assertion in a loaded situation. We try to break our system which is for call centers. We force the System to 10-20 calls per second and after some time we get an assert ioqueue_select.c line 363

   ```
 /* If safe unregistration (PJ_IOQUEUE_HAS_SAFE_UNREG) is used, get
     * the key from the free list. Otherwise allocate a new one. 
     */
#if PJ_IOQUEUE_HAS_SAFE_UNREG

    /* Scan closing_keys first to let them come back to free_list */
    scan_closing_keys(ioqueue);

    pj_assert(!pj_list_empty(&ioqueue->free_list));   <--- here is the assertion
    if (pj_list_empty(&ioqueue->free_list)) {
	rc = PJ_ETOOMANY;
	goto on_return;
    }

    key = ioqueue->free_list.next;
    pj_list_erase(key);
#else
    key = (pj_ioqueue_key_t*)pj_pool_zalloc(pool, sizeof(pj_ioqueue_key_t)); #endif
```

Is there something known that breaks the library? We need this to be fixed as this will finally stop our services and so the whole software fails.

**Comment by TheQue42** [comment]
I am running into this as well, and I'd really like to know how to increate the limits, apart from the fact that the error scenario needs to be handled more gracefully.

**Comment by nanangizz** [comment]
The assertion is not the actual error handling, it is there to notify the developer (in the development stage) that the socket number limit setting may need to be increased. While in the deployment/production stage, where release mode is normally used (e.g: via compile flag `-DNDEBUG`), the assertion should not be raised, instead it is handled by the "if" block and returning error `PJ_ETOOMANY`.

**Comment by TheQue42** [comment]
In my case, since I read a bit sloppily and I actually just got the PJ_ETOOMANY error(not assert), the problem for me was actually that ALL TCP 50 connections were torn down, after the PJSIP side sent TCP-RST on the last over-the-top, incoming TCP connection. 
Trying to recreate the scenario a few days later all my attempts showed that yes, it was the pjsip side that sent the RST, **but** the following FIN's, where all sent by the _SIPp side_.

So I'll stop complaining until I manage to recreate a real error, and sorry for the disturbance :-)
