### ISSUE TITLE
[pjsua] enable_loopback variable in pjsua_acc_config

### ISSUE THREAD

**Issue by JochenJung** [pjsip/pjproject#2662]
Hello,

I'm developing an application with pjsua and gstreamer. I've pjmedia
disabled (built with the #define PJSUA_MEDIA_HAS_PJMEDIA 0).

Still, as I understand pjmedia is still being used by pjsua. Pjmedia still
opens media ports. To stop pjmedia opening those ports I'm adjusting the
pjsua_acc_config and set the use_loop_med_tp
<https://www.pjsip.org/pjsip/docs/html/structpjsua__acc__config.htm#a4aa58f914064be2397463cdeb43dc5c9>
to true.

Reading further, there is a config variable enable_loopback
<https://www.pjsip.org/pjsip/docs/html/structpjsua__acc__config.htm#a0d3b3ffd08d8a162a2ed51810532a5eb>.
The documentation recommends to set this to true when use_loop_med_tp is
enabled.

What does enabling "enable_loopback" do and why should I enable it?

Thanks for the help.

Regards
Jochen Jung

**Comment by sauwming** [comment]
I don't know how to explain it better other than what's already written in the doc:
`If enabled, packets sent to the transport will be sent back to the streams attached to the transport.`

And I don't understand where you get the impression that the doc recommends to set it to true, since the default is false.

If you're not sure what it does, chance is that you don't need it, so you don't need to worry about it.

For further questions, please use any other means such as StackOverflow. Currently the issue page is for bug report or feature request only.
