### ISSUE TITLE
A place for application data inside struct pjmedia_port::port_data

### ISSUE THREAD

**Issue by hamstie** [pjsip/pjproject#2748]
it would be nice to have a place for application data inside 
pjmedia_port::port_data that will not be touched from conference bridge
e.g.

`   /** Port data can be used by the port creator to attach arbitrary`
`     *  value to be associated with the port.`
`     */`
`    struct port_data {`
`        void            *pdata;             /** Pointer data.      *`/
`        long             ldata;             /** Long data.         */`
`        void            *pdata_app;    /** Application data     */`
`    } port_data;`

Example:
- application can attach conference-slot_id, 
- application can attach app_data in end-of streaming/file callbacks

**Comment by andreas-wehrmann** [comment]
What exactly is your use case?
The eof callbacks the library already offers usually allow the user to specify user data.

**Comment by hamstie** [comment]
My application struct/class hold the port pointer and the conference slot-id for one port, it would be nice to store the slot_id inside port object.
If i am using a media port-callback, i often store callref-objects as callback user_data not the app-main-object , it would be nice to have the slot_id inside port (to disconnect port for example)
(my use case)

**Comment by andreas-wehrmann** [comment]
I'm not sure this is the right approach; because the snippet that you posted is meant for the implementer of a port.
I for example have implemented custom media ports and used the _port_data_ for private parts of the port (i.e. to hold state information).
Basically, you're asking for an addition to the existing media port members _("user data")_
that will have no use for the port itself.
I'm not sure what Teluu's view on this is, but I would like to keep concerns separated.

The way to go is usually what you're doing already:
Keep the port instance and any additional information you need with it in some user defined struct.

Or if it's a real burden on you to not have this:
You can implement a custom media port that simply wraps another media port but holds the additional information that you need.

**Comment by hamstie** [comment]
> for example have implemented custom media ports and used the port_data for private parts of the port (i.e. to hold state information).

This was also my first approach, but  this is dangerous because the conference-bridge used port_data (master port and passive port operations)

**Comment by andreas-wehrmann** [comment]
> This was also my first approach, but this is dangerous because the conference-bridge used port_data (master port and passive port operations)

I've just reviewed [conference.c](https://github.com/pjsip/pjproject/blob/master/pjmedia/src/pjmedia/conference.c) and found that it's not actually dangerous because the two things you're talking about (master/passive port) are private ports implementations of the confbridge itself, so it's okay for the confbridge to use these members (in other terms: the confbridge is the implementer of these ports).
