### ISSUE TITLE
Swift pjsua2 - Add video support

### ISSUE THREAD

**Issue by Truong-Thanh-Quang** [pjsip/pjproject#3058]
Please add pjsua2 video support to ios-swift-pjsua2.
@emretufekci : Please advice me some where to go. Thanks!

**Comment by emretufekci** [comment]
Hi @Truong-Thanh-Quang ,

Actually what i done it is only sample project, i haven't included anything to the original pjsip. The project is just example of how can we wrap the pjsua library to be able to use it via swift.

So, just check the original pjsua/pjsua2 sample projects and then wrap the functions which one do you want. 

Check sample .cpp functions instead swift/objc projects because of we're handle all of them via our wrapper class.
.CPP<->Obj-C++<->Obj-C<->Swift

**Comment by Truong-Thanh-Quang** [comment]
Thank you, Emre TUFEKCI.

**Comment by sauwming** [comment]
Please check #3381
