### ISSUE TITLE
Add ioqueue wakeup mechanism

### ISSUE THREAD

**Issue by jimying** [pjsip/pjproject#3160]
**Why add this feature?**

Suppose ioqueue poll timeout is 5 seconds

Cases:
  1. For ioqueue-select framework. When register a new socket to ioqueue, poll
 maybe blocked waiting, the new socket's events can't be real-time caught.
 Because the new socket has not added to select's read set.
 It'll be delay added to select read set until  exit waiting state and poll again.
 
 3. For ioqueue all frameworks. when exit app, poll maybe blocked waiting, it'll block until timeout.

 5. For ioqueue all frameworks.  Add a new timer, which's timeout value is
 small. If the ioqueue poll blocked waiting, the timer will
 be trigged more later than expected.

**Describe the solution you'd like**

Wakeup mechanism can solve above cases' problem, it will send
event to ioqueue and make it exit blocked waiting state immediately. <br>

Wakeup mechanism how to work:
When create ioqueue,  
use socketpair() to create  two sockets(one for read, the other for write),
and register the read socket to ioqueue.
When need wakeup the ioqueue,   write 1 byte to the write-side socket 
which will tigger the read-side socket to read.

** related **/
#3086 , if has wakup mechanism,  no need set poll timeout to a small value.

<br>

If you agree it, i'll find a time to create a new PR for this feature.

**Comment by sauwming** [comment]
Thanks for the suggestion, as well as very quickly (!) coming up with the implementation in #3086. We had a similar dream from a long time ago in #1125, which we eventually close since we didn't have time to implement.

The socket pair idea seems to be working fine, although I'm not sure if it's justifiable to use double the amount of the socket resources (i.e. `2*n`) just for the purpose of immediate wakeup. But since it's the only solution we have right now, we really appreciate it and hope you can keep it available for everyone so they can test it.

For now, I think no action is needed from your side. Let's wait first to hear from others if they require the wakeup feature and whether the socket pair mechanism is sufficient for their requirement.

Thanks again.

**Comment by jimying** [comment]
@sauwming 
I have implement this feature, please help review it.
