### ISSUE TITLE
Any plan to support websocket transport?

### ISSUE THREAD

**Issue by jimying** [pjsip/pjproject#3239]
Is pjproject  plan to support websocket transport?

Mybe we can firstly write the websocket library.

I have written some code, maybe give some help. Here is my test code project:
[pjwebsock](https://github.com/jimying/pjwebsock)
which is based on pjlib.

The Code has been tested good as client and server on linux x86_64
But the code is  ugly, should continue develop:
  -  independent http layer (http encode/decode)
  -  transport layer should more general (not only for websocket)
  -  thread safe

**Comment by sauwming** [comment]
At the moment, we don't have any plan to support it since there was rarely any request for this, but it definitely can change in the future.

I checked your project and it looks promising for a start. So if we receive any enquiries about this, I will be sure to recommend them to take a look at your project.

You seem to have great, novel ideas for some PJSIP enhancements (such as epoll, kqueue, socket pairs, and web socket), as well as come up with amazingly fast (!) implementation for those, which makes me wonder what project/development you are currently doing and whether you also need those enhancements for your own project.

**Comment by moradi-morteza** [comment]
sip over websocket is very important 
is there any new news about it?

**Comment by datpt11** [comment]
> sip over websocket is very important is there any new news about it?

same
