### ISSUE TITLE
~5x RSS memory increase with 9b37e587bc901d65ef5ca7b4ddeb5b9ac2c5267f (2.12 and newer)

### ISSUE THREAD

**Issue by mscdex** [pjsip/pjproject#3278]
### Describe the bug

9b37e587bc901d65ef5ca7b4ddeb5b9ac2c5267f (determined via git bisect) results in a ~5x RSS memory increase with a basic, non-SRTP, non-ICE, non-TURN, audio-only pjsua-based app immediately on startup/init. I briefly looked at the changes and didn't see any obvious causes. valgrind seems to report that the extra memory is all still reachable.

I also tried the latest commit on the master branch (currently 74569f926a2f553006d4bbac70c7371dfb1eb400) and the memory issue still existed.

If I revert (only) the problematic commit on either master or 2.12/2.12.1, the increased RSS memory usage issue goes away.

### Steps to reproduce

1. Create and start a very basic pjsua app -- no calls needed
2. Observe (immediate) RSS usage in a tool such as htop

### PJSIP version

multiple

### Context

- Tested on Linux 5.4.0
- `config_site.h`:

  ```
  #define PJ_SCANNER_USE_BITWISE 0
  #undef PJ_OS_HAS_CHECK_STACK
  #define PJ_OS_HAS_CHECK_STACK  0
  #define PJ_IOQUEUE_MAX_HANDLES 8192
  #define PJSIP_MAX_TSX_COUNT    ((640*1024)-1)
  #define PJSIP_MAX_DIALOG_COUNT ((640*1024)-1)
  #define PJ_DEBUG     0
  #define PJSIP_SAFE_MODULE    0
  #define PJ_HAS_STRICMP_ALNUM   0
  #define PJSUA_MAX_CALLS    4096
  #define PJMEDIA_HAS_SPEEX_AEC 0
  #define PJSUA_MAX_PLAYERS     4096
  #define PJSUA_MAX_RECORDERS     4096
  #define PJSUA_MAX_CONF_PORTS    (PJSUA_MAX_CALLS+2*PJSUA_MAX_PLAYERS)
  #define PJMEDIA_ADVERTISE_RTCP      0
  #define PJSIP_MAX_URL_SIZE (384)
  #define PJ_LOG_MAX_LEVEL   5
  #define PJMEDIA_HAS_SRTP 0
  #define PJMEDIA_HAS_VIDEO 0
  #define PJ_ENABLE_EXTRA_CHECK 1
  #undef PJ_HASH_USE_OWN_TOLOWER
  #undef PJSIP_UNESCAPE_IN_PLACE
  #undef PJ_TODO
  #define PJ_TODO(x)
  ```

### Log, call stack, etc

```shell
n/a
```

**Comment by sauwming** [comment]
You're right!!
And thanks for pointing out the exact commit that causes the issue.

The problem is the addition of `pjmedia_stream_info` to `pjsua_call_media`. The size of the structure itself is "only" 2k, but since in your case, your max calls is 4K, it quickly multiplies by a lot.
To be precise: 4K * 16 (PJSUA_MAX_CALL_MEDIA) * 2 (media+prov_media) * 2 (audio&video stream info) * 2K (sizeof(struct)) = 512 MB!!!

A workaround for this is to reduce PJSUA_MAX_CALL_MEDIA to 2 (enough for audio+video) or even 1, since you don't seem to use video. The memory usage will then become 64/32 MB respectively.

But of course that's still not ideal. I will try to create a patch tomorrow.
