### ISSUE TITLE
Crash in ssl_get_srtp_material() when invoking dtls_media_stop() in transport_srtp_dtls.c

### ISSUE THREAD

**Issue by bjptwist** [pjsip/pjproject#3299]
### Describe the bug

If **_dtls_media_stop()_** is invoked simultaneously with **_ssl_flush_wbio()_** both methods would have a sync point for a little while while waiting on **_pjmedia_clock_stop()_**.

snippet from **_ssl_flush_wbio()_**:
```
    ds->nego_completed = PJ_TRUE;
    PJ_LOG(2,(ds->base.name, "DTLS-SRTP negotiation completed!"));

    /* Stop the retransmission clock. Note that the clock may not be stopped
     * if this function is called from clock thread context. We'll try again
     * later in socket context.
     */
    if (ds->clock)
    pjmedia_clock_stop(ds->clock);

    /* Get SRTP key material */
    status = ssl_get_srtp_material(ds);
```

snippet from **_dtls_media_stop()_**:
```
#if DTLS_DEBUG
    PJ_LOG(2,(ds->base.name, "dtls_media_stop()"));
#endif

    if (ds->clock)
	pjmedia_clock_stop(ds->clock);
    
    /* Reset DTLS state */
    ssl_destroy(ds);
```

If the scenario described above happens, after **_pjmedia_clock_stop()_** returns, there may be a very likely scenario of _**ssl_destroy()**_ being invoked (from within **_dtls_media_stop()_**) and right after it **_ssl_get_srtp_material()_** (from within **_ssl_flush_wbio()_**). This causes a crash when attempting to access the null pointer of _ds->ossl_ssl_.

### Steps to reproduce

Here are some possible steps that can lead to the crash:

1. **_dtls_media_stop()_** is invoked and waits on **_pjmedia_clock_stop()_**
2. ** _ssl_flush_wbio()_** is invoked and waits on **_pjmedia_clock_stop()_**
3. after  **_pjmedia_clock_stop()_** returns on both methods, **_ssl_destroy(ds)_** executes and right after it **_ssl_get_srtp_material(ds)_**

### PJSIP version

2.12.1

### Context

This was tested on Android and iOS devices.

### Log, call stack, etc

```shell
Given the description and the steps to reproduce described above I think logs are not relevant here.
```

**Comment by bjptwist** [comment]
After analyzing the code I can see there are no sync structures to protect concurrent access to openssl related variables in transport_srtp_dtls.c. I've managed to solve the issue with this [patch](https://github.com/pjsip/pjproject/files/10126504/fix.txt).

Although it's quite a simple and straightforward solution, can you consider integrating it into the project's code base. Or if you come up with a better approach give some feedback? Thanks in advance.

**Comment by sauwming** [comment]
It looks like the problem is introduced because of the attempt to fix #3298.
The current behaviour is that `pjmedia_clock_stop()` doesn't wait, and when it has completed (provided that it's not called from its own thread), the callback should have also completed (since the clock thread has been successfully joined). So when `ssl_destroy()` is called from `dtls_media_stop()`, `ssl_flush_wbio()` should have completed, and the issue shouldn't happen.

So my proposed fix for #3298 was incorrect, let us find a way to fix it without introducing this issue.

**Comment by bjptwist** [comment]
I understand you are assuming _ssl_flush_wbio_ is solely invoked by _clock_thread_, which is not true.
In this case the _ssl_flush_wbio_ is being invoked by _ssl_on_recv_packet_. As I've stated before, this seems to be a simple concurrency problem of having multiple threads from unrelated contexts accessing the same resources at the same time (in this case ossl_* structures).

I've uploaded the stack trace of the two concurrent threads:

![Screen Shot 2022-12-05 at 13 29 06](https://user-images.githubusercontent.com/956797/205648919-e9a8770f-3cba-41d1-88c9-afd75d0f3354.png)

![Screen Shot 2022-12-05 at 13 29 49](https://user-images.githubusercontent.com/956797/205649064-c5520f15-c101-4ad6-b973-8d73bd84882a.png)

**Comment by sauwming** [comment]
The stack trace helps a lot.

It is a race between stop and recv, and locking does work to handle the race but it's not ideal since `transport_media_stop()` should actually guarantee that any media has completely stopped, i.e. to wait until the current ioq callback completes as well as prevent any future callbacks.

So my idea in the patch below is to try to stop the member transport first. Let me know if it works.
[dtls_race_stop_recv.txt](https://github.com/pjsip/pjproject/files/10162875/dtls_race_stop_recv.txt)

**Comment by bjptwist** [comment]
I understand your point. I'll have a look and give feedback.

**Comment by sauwming** [comment]
According to @nanang, who implemented the DTLS media transport, the lock approach should be better.

So I put your patch in PR #3321 with some modifications:
- adding a couple of missing lock release in `clock_cb()` and `ssl_handshake()`, and 
- fixing the lock destroy that's done after the pool is released.

Please let us know if you have any feedback.

**Comment by bjptwist** [comment]
Thanks for your feedback. I too think we should go with the lock approach since I've experienced other concurrency problems with different stack trace. I look forward for the PR to be committed in the main branch.
