### ISSUE TITLE
Support for T-Online SIP accounts

### ISSUE THREAD

**Issue by oliverepper** [pjsip/pjproject#3305]
As of now pjsip cannot be used to connect to your SIP account that comes with your T-Online account. T-Online no longer has A, or AAAA records for tel.t-online.de. Instead you're required to query for the NAPTR record for tel.t-online.de to get the right name depending on the transport you want to use UDP, TCP, TLS. With that information you can query for a SRV record that gives you the right server. The current resolver in pjsip does not support this, if my understanding is right. Asterisk, for example, implements a custom resolver.

I think it would be great if pjsip would support that out of the box.

@sauwming Can you point me in the direction of implementing and using my own resolver with pjsip for the time beeing?

**Comment by oliverepper** [comment]
I have just found this document: https://www.pjsip.org/pjsip/docs/html/group__PJSIP__RESOLVE.htm
So now I am certain, that NAPTR querying is not supported, yet. Would be nice, though.

**Comment by sauwming** [comment]
Right, it's not supported. So you need to use the external resolver and use [pjsip_resolver_set_ext_resolver()](https://www.pjsip.org/pjsip/docs/html/group__PJSIP__RESOLVE.htm#gaa04be85a4c28ed636c095f999cf7c9d4).

Since you are our licensee, please feel free to contact us directly via email if you have further questions.
