### ISSUE TITLE
pj_base64_decode differential fail.

### ISSUE THREAD

**Issue by 0x34d** [pjsip/pjproject#3431]
### Describe the bug

`pj_base64_decode`  fail against OpenSSL.

### Steps to reproduce

My branch : https://github.com/0x34d/pjproject/tree/oss-fuzz-Ideal

Build:
```
git clone --depth=1 -b oss-fuzz-Ideal https://github.com/0x34d/pjproject.git pjsip

export CC=clang 
export CXX=clang++
export CFLAGS="-O1 -fno-omit-frame-pointer -gline-tables-only -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="$CFLAGS"
export LIB_FUZZING_ENGINE="-fsanitize=fuzzer"


./configure \
    --disable-ffmpeg --disable-ssl \
    --disable-speex-aec --disable-speex-codec \
    --disable-g7221-codec --disable-gsm-codec --disable-ilbc-codec \
    --disable-resample --disable-libsrtp --disable-libwebrtc --disable-libyuv

make dep
make all
make fuzz

```

Crash-bug:
```
./tests/fuzz/fuzz-crypto crash-e4a198feee0cf87a08c7aad3a1dbb1c0d8864965
```

### PJSIP version

2.13

### Context

- Linux Fedora 
```
clang version 15.0.7 (Fedora 15.0.7-1.fc37)
Target: x86_64-redhat-linux-gnu
```

### Log, call stack, etc

```shell
Doesn't matter
```

**Comment by 0x34d** [comment]
file : 
[crash-e4a198feee0cf87a08c7aad3a1dbb1c0d8864965.txt](https://github.com/pjsip/pjproject/files/10942417/crash-e4a198feee0cf87a08c7aad3a1dbb1c0d8864965.txt)

**Comment by sauwming** [comment]
Since your input contains newline, you need to set the no newline flag
```
    // Ignore newlines - write everything in one line
    BIO_set_flags(b64, BIO_FLAGS_BASE64_NO_NL);
```

Attached is the patch:
[decode_base64_fix.txt](https://github.com/pjsip/pjproject/files/10950985/decode_base64_fix.txt)

Also note that our `pj_base64_decode()` will silently ignore invalid characters, so the result may be different.
https://github.com/pjsip/pjproject/blob/master/pjlib-util/src/pjlib-util/base64.c#L142
