### ISSUE TITLE
on prview window how to flip a camera 

### ISSUE THREAD

**Issue by shubham795** [pjsip/pjproject#3508]
I'm using this code to flip a camera but it's not working.     
       ```
int cameraId = 2;
                
                CallVidSetStreamParam *callVidSetStreamParam = new CallVidSetStreamParam();
                callVidSetStreamParam->capDev = cameraId;
                call->vidSetStream(PJSUA_CALL_VID_STRM_CHANGE_CAP_DEV, * callVidSetStreamParam);
```
if anyone knows kindly please help me

**Comment by sauwming** [comment]
I'm sorry, but currently the issue page is for bug report or feature request only, not for asking enquiries.

As previously suggested, you can try with the sample app. I would recommend to try ipjsua since it has more complete feature set. Once you know it works fine in the ipjsua sample app (which is using pjsua API and in Obj-C), all you need to do is to port it to Swift, or find the corresponding pjsua2 API.
