### ISSUE TITLE
OPUS FEC statistics collection

### ISSUE THREAD

**Issue by vlsvs2009** [pjsip/pjproject#3573]
### Describe the bug

Hello, we are interested in collecting call quality statistics using various codecs, and for this purpose, we would like to gather more information from the codecs themselves. Specifically, codecs like PCMU do not provide any information, but codecs like OPUS can include FEC within SILK compression. It would be helpful to understand the amount of data obtained using error correction algorithms, i.e., where the actual utilization of redundant codec data was beneficial.

I believe such interesting statistics could be useful not only to us but also to other users. Therefore, I encourage discussing this matter and, if possible, sharing methods of obtaining such values.

I couldn't immediately find an API for retrieving statistics from within the codec itself, but I see that there is textual call statistics info showing jitter and other characteristics. Perhaps someone already has or knows some API methods for obtaining detailed encoding information. Please share your experiences.

### Steps to reproduce

N/A

### PJSIP version

2.13

### Context

Enhancement proposal

### Log, call stack, etc

```shell
N/A
```

**Comment by sauwming** [comment]
You can check the attached patch.
FEC/total_packet indicates the percentage FEC is used compared to the total number of packets, while PLC/total_packet is the percentage that normal PLC is used instead.
(FEC+PLC)/total_packet should represent the packet loss%.
FEC/(FEC+PLC) is the percentage of FEC used when packet loss happens.

[opus_fec.txt](https://github.com/pjsip/pjproject/files/11513564/opus_fec.txt)

**Comment by vlsvs2009** [comment]
Hello, thank you for a prompt response regarding this inquiry. The idea for suggested patch is clear and well looking, and as I understood, those calculations would be processed on pjmedia/pjmedia-codec level. Is it possible to pass proposed FEC/PLC calculations to the pjsua level, so they could be accessed through API methods currently available for other call statistic metrics?

**Comment by sauwming** [comment]
Unfortunately we don't have any pjmedia/pjmedia-codec API for that purpose. And considering that only Opus seems to need it (as of right now), adding a general codec API seems like an overkill.

For now, I would suggest to add your own API in `pjmedia-codec/opus.h`, such as `pjmedia_codec_opus_get_stat()`. Modifying library code is normally not recommended, but this time it should be okay since there's very minimal risk of conflict.

If in the future, there are more codecs that need this API or if there are more users that also wish for this feature, then we'll consider adding it to the library.
